version: 2

builds:
  - builder: zig
    binary: wch
    flags:
      - -Doptimize=ReleaseSafe
      - "-Dversion={{ .Version }}"
    targets:
      - x86_64-linux
      - aarch64-linux
      - x86_64-macos
      - aarch64-macos

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
