name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

jobs:
  release:
    uses: ivoronin/github-workflows/.github/workflows/release.yml@a56926c483d814dd0ab9543491d07ac64fd49b2f # main
    with:
      language: zig
      brew: true
    secrets: inherit
