name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

jobs:
  release:
    uses: ivoronin/github-workflows/.github/workflows/release.yml@41258c923b9066bccb4c4b0685013b49130f578a # main
    with:
      language: zig
      brew: true
    secrets: inherit
