name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    uses: ivoronin/github-workflows/.github/workflows/test.yml@41258c923b9066bccb4c4b0685013b49130f578a # main
    with:
      language: zig
